name: bd_mock_api
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"


#------------------------ PACKAGES ------------------------#

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  timeago: ^3.7.0
  get: ^4.6.6
  http: ^1.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  rename: ^3.0.2


#---------------------- DEV PACKAGES ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"



flutter:
  uses-material-design: true




#----------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/icons/ 
    - assets/images/
#----------------------- LOCAL FONTS -----------------------#
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
