name: bd_mock_api
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

#------------------------ PACKAGES ------------------------#

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

# State Management

# Utility Packages

#---------------------- DEV PACKAGES ----------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
#----------------------- LOCAL ASSETS ----------------------#
# assets:
# - images/a_dot_burr.jpeg

#----------------------- LOCAL FONTS -----------------------#
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
